version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.5.2
jobs:
  playwright-test:
    docker:
      - image: cimg/node:20.4.0-browsers
    parallelism: 4
    resource_class: large
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Run Playwright Tests
          command: |
            mkdir test-results
            pnpm run serve &
            TESTFILES=$(circleci tests glob "specs/e2e/**/*.spec.ts")
            echo "$TESTFILES" | circleci tests run --command="xargs pnpm playwright test --config=playwright.config.ci.ts --reporter=junit" --verbose --split-by=timings
      - store_test_results:
          path: test-results
workflows:
  test-workflow:
    jobs:
      - playwright-test