version: 2.1

orbs:
  cicd: sedstart/cicd@dev:1

jobs:
  run-sedstart-local-mac:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - cicd/runlocal:
          api_key: $SEDSTART_API_KEY_PROD
          project_id: 418
          test_id: 1937
          profile_id: 848
          browser: chrome
          headless: true
          environment: QA

workflows:
  main:
    jobs:
      - run-sedstart-local-mac
